# Generated by Django 3.2.7 on 2023-01-25 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mayapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='book_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='mayapp.bookcategory', verbose_name='категория книг'),
        ),
        migrations.AlterField(
            model_name='author',
            name='date_birthday',
            field=models.DateField(null=True, verbose_name='дата рождения'),
        ),
        migrations.AlterField(
            model_name='author',
            name='pseudonym',
            field=models.CharField(max_length=127, null=True, verbose_name='псевдоним'),
        ),
    ]
